#基础信息
title: fishedee的博客
email: 306766045@qq.com
url: fishedee.com
avatar: http://image.fishedee.com/FulTCoakq411USQX_3HiZ79_fH0i
description: 一个安静的程序猿

#文档配置
markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  enable_coderay: true
  syntax_highlighter: rouge
  coderay:
    coderay_line_numbers:  nil

#评论配置
disqus: fishedee

#统计配置
baidu: 0a6da8c751d798199236954c919fd59e


